services:
  nmdsuite:
    image: ghcr.io/hb9tvk/nmdsuite:latest
    container_name: nmdsuite
    pull_policy: always
    ports:
      - 127.0.0.1:5005:5005
    networks:
      - nginxproxy_default
      - postfix_default
    env_file:
      - .env
    environment:
      NMD_DB_PATH: /data/nmdsuite.sqlite3
    volumes:
      - ./data:/data
    restart: unless-stopped

networks:
  nginxproxy_default:
    external: true
  postfix_default:
    external: true
