# Generated by Django 5.1.15 on 2026-05-10 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                ("year", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("contest_date", models.DateField(help_text="UTC date of the contest")),
                ("start_utc", models.DateTimeField(help_text="Contest start (06:00 UTC)")),
                ("end_utc", models.DateTimeField(help_text="Contest end (09:59:59 UTC)")),
                ("half_split_utc", models.DateTimeField(help_text="Boundary between H1 and H2 (08:00 UTC)")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reg_open", "Registration open"),
                            ("reg_closed", "Registration closed"),
                            ("logs_open", "Log submission open"),
                            ("logs_closed", "Log submission closed"),
                            ("scored", "Scored"),
                            ("published", "Results published"),
                            ("archived", "Archived"),
                        ],
                        default="reg_open",
                        max_length=16,
                    ),
                ),
                ("results_published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed")],
                        default="queued",
                        max_length=8,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "contest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="core.contest",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "callsign",
                    models.CharField(help_text="Operator/station callsign without /P", max_length=20),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("multi_op", models.BooleanField(default=False)),
                ("station_chief", models.CharField(blank=True, max_length=20)),
                (
                    "coord_system_input",
                    models.CharField(
                        choices=[("wgs84", "WGS84"), ("ch1903", "CH1903"), ("ch1903plus", "CH1903+")],
                        max_length=12,
                    ),
                ),
                (
                    "coord_input_e",
                    models.CharField(
                        blank=True, help_text="Original easting/longitude as entered", max_length=32
                    ),
                ),
                (
                    "coord_input_n",
                    models.CharField(
                        blank=True, help_text="Original northing/latitude as entered", max_length=32
                    ),
                ),
                ("ch1903p_e", models.FloatField(blank=True, null=True)),
                ("ch1903p_n", models.FloatField(blank=True, null=True)),
                ("wgs84_lat", models.FloatField(blank=True, null=True)),
                ("wgs84_lon", models.FloatField(blank=True, null=True)),
                ("altitude_m", models.PositiveIntegerField()),
                ("canton", models.CharField(help_text="2-letter Swiss canton code", max_length=2)),
                (
                    "operating_modes",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "CW"), (2, "SSB"), (3, "CW + SSB")], default=3
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="core.contest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["callsign"],
                "unique_together": {("contest", "user")},
            },
        ),
        migrations.CreateModel(
            name="QsoEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("utc_time", models.DateTimeField()),
                ("mode", models.CharField(choices=[("CW", "CW"), ("SSB", "SSB")], max_length=3)),
                ("remote_call", models.CharField(max_length=20)),
                ("rsts", models.CharField(max_length=3)),
                ("txts", models.CharField(blank=True, max_length=255)),
                ("rstr", models.CharField(max_length=3)),
                ("txtr", models.CharField(blank=True, max_length=255)),
                ("remark", models.CharField(blank=True, max_length=255)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qsos",
                        to="core.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["utc_time"],
            },
        ),
        migrations.CreateModel(
            name="ScoringOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("utc_time", models.DateTimeField()),
                ("remote_call", models.CharField(max_length=20)),
                ("mode", models.CharField(max_length=3)),
                (
                    "forced_status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Unmatched NMD QSO"),
                            ("full_match", "Full NMD match"),
                            ("text_mismatch", "NMD match with text errors"),
                            ("hb9_qso", "Swiss non-NMD QSO"),
                            ("dx_qso", "DX QSO"),
                            ("admin_accepted", "Admin-accepted unmatched"),
                            ("dupe_deducted", "Duplicate (deducted)"),
                            ("suspected_call_mismatch", "Possibly wrong remote callsign"),
                        ],
                        max_length=32,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("decided_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scoring_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_overrides",
                        to="core.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoringRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Unmatched NMD QSO"),
                            ("full_match", "Full NMD match"),
                            ("text_mismatch", "NMD match with text errors"),
                            ("hb9_qso", "Swiss non-NMD QSO"),
                            ("dx_qso", "DX QSO"),
                            ("admin_accepted", "Admin-accepted unmatched"),
                            ("dupe_deducted", "Duplicate (deducted)"),
                            ("suspected_call_mismatch", "Possibly wrong remote callsign"),
                        ],
                        default="unmatched",
                        max_length=32,
                    ),
                ),
                ("points", models.PositiveSmallIntegerField(default=0)),
                ("text_distance", models.PositiveSmallIntegerField(default=0)),
                (
                    "half",
                    models.PositiveSmallIntegerField(default=1, help_text="1 = 06–08 UTC, 2 = 08–10 UTC"),
                ),
                ("suspected_correct_call", models.CharField(blank=True, max_length=20)),
                ("admin_overridden", models.BooleanField(default=False)),
                ("admin_comment", models.CharField(blank=True, max_length=255)),
                ("scored_at", models.DateTimeField(auto_now=True)),
                (
                    "matched_qso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_by",
                        to="core.qsoentry",
                    ),
                ),
                (
                    "qso",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="score", to="core.qsoentry"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("op_name", models.CharField(blank=True, max_length=80)),
                ("location_text", models.CharField(blank=True, max_length=120)),
                (
                    "qah_m",
                    models.PositiveIntegerField(
                        blank=True, help_text="Antenna height above ground", null=True
                    ),
                ),
                ("watt", models.CharField(blank=True, max_length=20)),
                (
                    "total_weight_g",
                    models.PositiveIntegerField(
                        default=0, help_text="Total station weight (grams) — used as ranking tiebreaker"
                    ),
                ),
                ("submitted", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station",
                        to="core.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station description",
                "verbose_name_plural": "Station descriptions",
            },
        ),
        migrations.CreateModel(
            name="StationComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idx", models.PositiveSmallIntegerField()),
                ("description", models.CharField(max_length=120)),
                ("weight_g", models.PositiveIntegerField(default=0)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="core.stationdescription",
                    ),
                ),
            ],
            options={
                "ordering": ["idx"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_label",
                    models.CharField(blank=True, help_text="Free-text actor (e.g. 'system')", max_length=80),
                ),
                ("action", models.CharField(max_length=64)),
                ("target", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit",
                        to="core.contest",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="core_auditl_timesta_189a84_idx"),
                    models.Index(fields=["action"], name="core_auditl_action_d9fb24_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="qsoentry",
            index=models.Index(fields=["participant", "utc_time"], name="core_qsoent_partici_a8a2df_idx"),
        ),
        migrations.AddIndex(
            model_name="qsoentry",
            index=models.Index(
                fields=["remote_call", "mode", "utc_time"], name="core_qsoent_remote__cb7617_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scoringoverride",
            unique_together={("participant", "utc_time", "remote_call", "mode")},
        ),
        migrations.AlterUniqueTogether(
            name="stationcomponent",
            unique_together={("station", "idx")},
        ),
    ]
