# Generated by Django 5.1.15 on 2026-05-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_merge_station_into_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qsoentry",
            name="txtr",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="qsoentry",
            name="txts",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
