# Generated by Django 5.1.15 on 2026-05-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_invalid_callsign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invalidcallsign",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
